/**
 * @fileoverview gRPC-Web generated client stub for library.LibraryService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./library_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.LibraryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';
  this.client_ = new grpc.web.GrpcWebClientBase(options);
  this.hostname_ = hostname.replace(/\/+$/, '');
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.LibraryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';
  this.client_ = new grpc.web.GrpcWebClientBase(options);
  this.hostname_ = hostname.replace(/\/+$/, '');
};

// ─── GetBook ──────────────────────────────────────────────────────────────────

const methodDescriptor_LibraryService_GetBook = new grpc.web.MethodDescriptor(
  '/library.LibraryService/GetBook',
  grpc.web.MethodType.UNARY,
  proto.BookRequest,
  proto.BookResponse,
  function(request) { return request.serializeBinary(); },
  proto.BookResponse.deserializeBinary
);

proto.LibraryServiceClient.prototype.getBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/library.LibraryService/GetBook',
      request, metadata || {},
      methodDescriptor_LibraryService_GetBook,
      callback);
};

proto.LibraryServicePromiseClient.prototype.getBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/library.LibraryService/GetBook',
      request, metadata || {},
      methodDescriptor_LibraryService_GetBook);
};

// ─── ListBooks ────────────────────────────────────────────────────────────────

const methodDescriptor_LibraryService_ListBooks = new grpc.web.MethodDescriptor(
  '/library.LibraryService/ListBooks',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.BookList,
  function(request) { return request.serializeBinary(); },
  proto.BookList.deserializeBinary
);

proto.LibraryServiceClient.prototype.listBooks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/library.LibraryService/ListBooks',
      request, metadata || {},
      methodDescriptor_LibraryService_ListBooks,
      callback);
};

proto.LibraryServicePromiseClient.prototype.listBooks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/library.LibraryService/ListBooks',
      request, metadata || {},
      methodDescriptor_LibraryService_ListBooks);
};

// ─── CreateBook ───────────────────────────────────────────────────────────────

const methodDescriptor_LibraryService_CreateBook = new grpc.web.MethodDescriptor(
  '/library.LibraryService/CreateBook',
  grpc.web.MethodType.UNARY,
  proto.CreateBookRequest,
  proto.BookResponse,
  function(request) { return request.serializeBinary(); },
  proto.BookResponse.deserializeBinary
);

proto.LibraryServiceClient.prototype.createBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/library.LibraryService/CreateBook',
      request, metadata || {},
      methodDescriptor_LibraryService_CreateBook,
      callback);
};

proto.LibraryServicePromiseClient.prototype.createBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/library.LibraryService/CreateBook',
      request, metadata || {},
      methodDescriptor_LibraryService_CreateBook);
};

// ─── UpdateBook ───────────────────────────────────────────────────────────────

const methodDescriptor_LibraryService_UpdateBook = new grpc.web.MethodDescriptor(
  '/library.LibraryService/UpdateBook',
  grpc.web.MethodType.UNARY,
  proto.UpdateBookRequest,
  proto.BookResponse,
  function(request) { return request.serializeBinary(); },
  proto.BookResponse.deserializeBinary
);

proto.LibraryServiceClient.prototype.updateBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/library.LibraryService/UpdateBook',
      request, metadata || {},
      methodDescriptor_LibraryService_UpdateBook,
      callback);
};

proto.LibraryServicePromiseClient.prototype.updateBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/library.LibraryService/UpdateBook',
      request, metadata || {},
      methodDescriptor_LibraryService_UpdateBook);
};

// ─── DeleteBook ───────────────────────────────────────────────────────────────

const methodDescriptor_LibraryService_DeleteBook = new grpc.web.MethodDescriptor(
  '/library.LibraryService/DeleteBook',
  grpc.web.MethodType.UNARY,
  proto.BookRequest,
  proto.DeleteBookResponse,
  function(request) { return request.serializeBinary(); },
  proto.DeleteBookResponse.deserializeBinary
);

proto.LibraryServiceClient.prototype.deleteBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/library.LibraryService/DeleteBook',
      request, metadata || {},
      methodDescriptor_LibraryService_DeleteBook,
      callback);
};

proto.LibraryServicePromiseClient.prototype.deleteBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/library.LibraryService/DeleteBook',
      request, metadata || {},
      methodDescriptor_LibraryService_DeleteBook);
};

module.exports = proto;
