/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.3
// source: proto/library.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./library_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.LibraryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.LibraryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.BookRequest,
 *   !proto.BookResponse>}
 */
const methodDescriptor_LibraryService_GetBook = new grpc.web.MethodDescriptor(
  '/LibraryService/GetBook',
  grpc.web.MethodType.UNARY,
  proto.BookRequest,
  proto.BookResponse,
  /**
   * @param {!proto.BookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.BookResponse.deserializeBinary
);


/**
 * @param {!proto.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.LibraryServiceClient.prototype.getBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/LibraryService/GetBook',
      request,
      metadata || {},
      methodDescriptor_LibraryService_GetBook,
      callback);
};


/**
 * @param {!proto.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.BookResponse>}
 *     Promise that resolves to the response
 */
proto.LibraryServicePromiseClient.prototype.getBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/LibraryService/GetBook',
      request,
      metadata || {},
      methodDescriptor_LibraryService_GetBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Empty,
 *   !proto.BookList>}
 */
const methodDescriptor_LibraryService_ListBooks = new grpc.web.MethodDescriptor(
  '/LibraryService/ListBooks',
  grpc.web.MethodType.UNARY,
  proto.Empty,
  proto.BookList,
  /**
   * @param {!proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.BookList.deserializeBinary
);


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.BookList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.BookList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.LibraryServiceClient.prototype.listBooks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/LibraryService/ListBooks',
      request,
      metadata || {},
      methodDescriptor_LibraryService_ListBooks,
      callback);
};


/**
 * @param {!proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.BookList>}
 *     Promise that resolves to the response
 */
proto.LibraryServicePromiseClient.prototype.listBooks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/LibraryService/ListBooks',
      request,
      metadata || {},
      methodDescriptor_LibraryService_ListBooks);
};


module.exports = proto;

